### ISSUE TITLE
ERROR: Access is denied!

### ISSUE THREAD

**Issue by razandtim** [willnode/autobloom#1]
I tried to reinstall it but it cannot install "AUTOBLOOM". It says "ERROR: Access is denied!". I also run it as administrator but same thing.

![image](https://user-images.githubusercontent.com/74573568/142756820-a4d23fe0-0fca-468f-bd93-24b0c1527b55.png)

**Comment by ericshu6** [comment]
did you run uninstall.bat?

**Comment by eltrevii** [comment]
this issue will be closed because there hasnt been any activity in a long time
