### ISSUE TITLE
detected as virus

### ISSUE THREAD

**Issue by engi-gaming** [willnode/autobloom#12]
i wanted to use this, but it is detected as a virus by virustotal

**Comment by engi-gaming** [comment]
https://www.virustotal.com/gui/file/50cecbfc761e4e4170100a67f68dc210c95d0e902e3c76fdae8ff1a57cb41fc2?nocache=1

**Comment by willnode** [comment]
Ok, the virus total link you mention got me thinking.
I should release a version with no EXE's that I build myself.

**Comment by mikromik42069** [comment]
> Ok, the virus total link you mention got me thinking. I should release a version with no EXE's that I build myself.

Yes you should (15 months ago 🤣)

**Comment by eltrevii** [comment]
fixed @ #16

**Comment by eltrevii** [comment]
https://www.virustotal.com/gui/file/c4d0e098ca71db2645097d6535b41835e1ed09184bd608d4a326f42f6e3de775?nocache=1

**Comment by Micromic0** [comment]
By the way you cannot add a virus by accident. It can ONLY be on purpose. So if they say that they accidentally added a virus, they are 100% lying to you and just want to scam you.

**Comment by eltrevii** [comment]
@mikromik42069 no one added a virus. its just a false positive because the executables arent signed or something and also because it changes a windows setting
