### ISSUE TITLE
Considering to use runtime script to bypass "virus" issue.

### ISSUE THREAD

**Issue by willnode** [willnode/autobloom#15]
The background change uses VB to call in windows API. We compile that VB to EXE so people don't have to install Visual Studio to make that work. But windows seems doesn't nice to any kind of unsigned executable files... 

I'm considering replacing that VB with some runtime executable, like Node JS. This should effectively solve the "detected as virus" issue.

**Comment by eltrevii** [comment]
fixed @ #16 👍🏻
