### ISSUE TITLE
Doesn't work? Consider this.

### ISSUE THREAD

**Issue by willnode** [willnode/autobloom#2]
Welp, despite being simple in theory, messing with windows internal is really a mess. A lot of people say this software didn't work, mostly because of being falsely reported as a virus (because all apps are not signed right now and it's out of my reach currently). You can either recompile the scripts or just add the auto bloom folder you've downloaded as an exclusion.

All this software is doing is: (1) play the video in the background, (2) make it run during logon.

I'm considering an alternative to the scripts but have no sweet solution yet. That's takes time.

**Comment by amauryjaphet** [comment]
I agree tho. They need to make an update for windows 11 for the _bloom backgrounds_ to animate

**Comment by askfriends** [comment]
What about dark theme? will u consider adding dark version too?
and it would be nice if you add reverse animation when we click log off or shutdown pc

**Comment by Zynachu** [comment]
> What about dark theme? will u consider adding dark version too? and it would be nice if you add reverse animation when we click log off or shutdown pc

adding dark theme to the animation is a bit harder, since ms only animates the light theme only.

**Comment by amauryjaphet** [comment]
If you have frame-gui or flow frames you can interpolate the video to the MAX. fps (i recommend on frame-gui because flow frames is slow)

**Comment by eltrevii** [comment]
> this software didn't work, mostly because of being falsely reported as a virus

fixed @ #16
