### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by ghost** [willnode/autobloom#3]
When i try to download the file it says that has a virus, and there isnt any way to download it.

**Comment by guywhoreportsissues** [comment]
You could try it in firefox. And allow the download. And when you run the file click more info and run.

**Comment by schroef** [comment]
Whats your browser?

If its Chrome you can easily by pass it

**Comment by schroef** [comment]
If you see this in Chrome, then check the second image how to simply save it.
Error showing in Chrome
![Screen Shot 2022-02-22 at 16 02 25](https://user-images.githubusercontent.com/6923008/155210097-5548443d-ef4d-4079-9e9e-4045e71d5ed6.png)

Easy to bypass
![Screen Shot 2022-02-22 at 16 02 59](https://user-images.githubusercontent.com/6923008/155210140-d77a6416-2b06-4574-84a0-9616f36e0008.png)

**Comment by eltrevii** [comment]
fixed @ #16
